evie_mcp:
    cache_ttl: 300
    servers:
        filesystem:
            transport: 'http'
            url: '%env(default:MCP_FILESYSTEM_URL:default:http://mcp-filesystem:8123)%'
        playwright:
            transport: 'http'
            url: '%env(default:MCP_PLAYWRIGHT_URL:default:http://mcp-playwright:8931/mcp)%'
        github:
            transport: 'http'
            url: '%env(default::GITHUB_MCP_URL)%'
