<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Erstellt die users-Tabelle mit onboarding_complete-Flag (Frontend-Audit F4).
 *
 * Main's Schema-Migration (Version20260818081106) erstellt nur user_profile,
 * nicht die users-Tabelle. Diese Migration ergaenzt die users-Tabelle, die von
 * der User-Entity (ORM\Table(name: 'users')) benoetigt wird.
 *
 * Frontend-Audit F4: Neuer User hat onboarding_complete=false, sodass der
 * Onboarding-Flow nach Login getriggert werden kann (OnboardingController + Popup).
 */
final class Version20260819000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Erstellt users-Tabelle mit onboarding_complete boolean column (Frontend-Audit F4).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, onboarding_complete BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE users');
    }
}
