<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260818081106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action TEXT NOT NULL, details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, sub_agent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5E912E1A76ED395 ON agent_history (user_id)');
        $this->addSql('CREATE INDEX IDX_F5E912E18EBB9F52 ON agent_history (sub_agent_id)');
        $this->addSql('CREATE TABLE ai_mcp_server_definitions (id UUID NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, description TEXT NOT NULL, configuration JSON NOT NULL, is_active BOOLEAN NOT NULL, allowed_tools JSON NOT NULL, blocked_resources JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78F351885E237E06 ON ai_mcp_server_definitions (name)');
        $this->addSql('CREATE INDEX IDX_78F35188B03A8386 ON ai_mcp_server_definitions (created_by_id)');
        $this->addSql('CREATE TABLE ai_streaming_sessions (id UUID NOT NULL, session_id VARCHAR(255) NOT NULL, tool_name VARCHAR(255) NOT NULL, initial_arguments JSON NOT NULL, user_identifier VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, current_progress TEXT DEFAULT NULL, progress_percentage DOUBLE PRECISION DEFAULT NULL, partial_results JSON DEFAULT NULL, final_result JSON DEFAULT NULL, error_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, correlation_id VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E47153B1613FECDF ON ai_streaming_sessions (session_id)');
        $this->addSql('CREATE INDEX IDX_E47153B1A76ED395 ON ai_streaming_sessions (user_id)');
        $this->addSql('CREATE TABLE ai_sub_agent_definitions (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, class_name VARCHAR(255) NOT NULL, configuration JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D9950EB7B03A8386 ON ai_sub_agent_definitions (created_by_id)');
        $this->addSql('CREATE TABLE decision_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, decision TEXT NOT NULL, context TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB53662BA76ED395 ON decision_log (user_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, file_path VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, agent_history_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76A76ED395 ON document (user_id)');
        $this->addSql('CREATE INDEX IDX_D8698A766F43555D ON document (agent_history_id)');
        $this->addSql('CREATE TABLE sub_agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, capabilities JSON DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CACFF824A76ED395 ON sub_agent (user_id)');
        $this->addSql('CREATE TABLE tool_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tool_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, tool_schema JSON NOT NULL, parameters JSON DEFAULT NULL, status VARCHAR(50) NOT NULL, complexity VARCHAR(50) DEFAULT NULL, dependencies JSON DEFAULT NULL, metadata JSON DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E59DC75912469DE2 ON tool_definition (category_id)');
        $this->addSql('CREATE TABLE user_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, user_identifier VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, preferences JSON DEFAULT NULL, user_type VARCHAR(255) DEFAULT NULL, context_embedding TEXT DEFAULT NULL, onboarding_data JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95AB405D0494586 ON user_profile (user_identifier)');
        $this->addSql('ALTER TABLE agent_history ADD CONSTRAINT FK_F5E912E1A76ED395 FOREIGN KEY (user_id) REFERENCES user_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agent_history ADD CONSTRAINT FK_F5E912E18EBB9F52 FOREIGN KEY (sub_agent_id) REFERENCES sub_agent (id)');
        $this->addSql('ALTER TABLE ai_mcp_server_definitions ADD CONSTRAINT FK_78F35188B03A8386 FOREIGN KEY (created_by_id) REFERENCES user_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ai_streaming_sessions ADD CONSTRAINT FK_E47153B1A76ED395 FOREIGN KEY (user_id) REFERENCES user_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ai_sub_agent_definitions ADD CONSTRAINT FK_D9950EB7B03A8386 FOREIGN KEY (created_by_id) REFERENCES user_profile (id)');
        $this->addSql('ALTER TABLE decision_log ADD CONSTRAINT FK_BB53662BA76ED395 FOREIGN KEY (user_id) REFERENCES user_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76A76ED395 FOREIGN KEY (user_id) REFERENCES user_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A766F43555D FOREIGN KEY (agent_history_id) REFERENCES agent_history (id)');
        $this->addSql('ALTER TABLE sub_agent ADD CONSTRAINT FK_CACFF824A76ED395 FOREIGN KEY (user_id) REFERENCES user_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tool_definition ADD CONSTRAINT FK_E59DC75912469DE2 FOREIGN KEY (category_id) REFERENCES tool_category (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent_history DROP CONSTRAINT FK_F5E912E1A76ED395');
        $this->addSql('ALTER TABLE agent_history DROP CONSTRAINT FK_F5E912E18EBB9F52');
        $this->addSql('ALTER TABLE ai_mcp_server_definitions DROP CONSTRAINT FK_78F35188B03A8386');
        $this->addSql('ALTER TABLE ai_streaming_sessions DROP CONSTRAINT FK_E47153B1A76ED395');
        $this->addSql('ALTER TABLE ai_sub_agent_definitions DROP CONSTRAINT FK_D9950EB7B03A8386');
        $this->addSql('ALTER TABLE decision_log DROP CONSTRAINT FK_BB53662BA76ED395');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76A76ED395');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A766F43555D');
        $this->addSql('ALTER TABLE sub_agent DROP CONSTRAINT FK_CACFF824A76ED395');
        $this->addSql('ALTER TABLE tool_definition DROP CONSTRAINT FK_E59DC75912469DE2');
        $this->addSql('DROP TABLE agent_history');
        $this->addSql('DROP TABLE ai_mcp_server_definitions');
        $this->addSql('DROP TABLE ai_streaming_sessions');
        $this->addSql('DROP TABLE ai_sub_agent_definitions');
        $this->addSql('DROP TABLE decision_log');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE sub_agent');
        $this->addSql('DROP TABLE tool_category');
        $this->addSql('DROP TABLE tool_definition');
        $this->addSql('DROP TABLE user_profile');
    }
}
