<?php
namespace App\AI\Skills;

use App\Entity\ToolDefinition;
use App\Repository\ToolDefinitionRepository;
use Symfony\AI\Platform\PlatformInterface;
use Symfony\AI\Platform\Response\ResponseFormatFactory;

/**
 * Generiert Tool-Definitionen basierend auf User-Anfragen.
 * Nutzt Mistral, um JSON-Schemata für neue Tools zu erstellen.
 */
class ToolDefinitionGenerator
{
    private ToolDefinitionRepository $toolDefinitionRepo;
    private PlatformInterface $platform;

    public function __construct(
        ToolDefinitionRepository $toolDefinitionRepo,
        PlatformInterface $platform
    ) {
        $this->toolDefinitionRepo = $toolDefinitionRepo;
        $this->platform = $platform;
    }

    /**
     * Generates a new tool definition based on the user's need.
     * Uses the LLM to generate a proper JSON schema for the tool.
     */
    public function generateToolDefinition(string $toolName, string $description, array $context = []): ToolDefinition
    {
        // Use the LLM to generate a schema for the tool
        $schema = $this->generateSchemaWithLLM($toolName, $description, $context);

        $toolDefinition = new ToolDefinition();
        $toolDefinition->setName($toolName);
        $toolDefinition->setDescription($description);
        $toolDefinition->setSchema($schema);
        $toolDefinition->setParameters($this->extractParametersFromSchema($schema));
        $toolDefinition->setStatus('pending'); // Default status is pending

        // Save to database
        $this->toolDefinitionRepo->save($toolDefinition, true);

        return $toolDefinition;
    }

    /**
     * Uses the LLM to generate a JSON schema for a tool.
     */
    private function generateSchemaWithLLM(string $toolName, string $description, array $context = []): array
    {
        // Create a prompt for the LLM to generate a JSON schema
        $prompt = sprintf(
            "Generate a JSON schema for a tool named '%s' with the description: '%s'. " .
            "The schema should be a valid JSON Schema object with properties, types, descriptions, and required fields. " .
            "Return only the JSON schema, without any additional text.",
            $toolName,
            $description
        );

        // Use the platform to get a structured response
        $responseFormat = ResponseFormatFactory::createJson();
        $response = $this->platform->generate($prompt, $responseFormat);

        // Parse the response to get the schema
        $schema = json_decode($response->getContent(), true);

        // Ensure the schema is valid
        if (!isset($schema['type']) || $schema['type'] !== 'object') {
            throw new \RuntimeException('Invalid schema generated by LLM.');
        }

        return $schema;
    }

    /**
     * Extracts parameters from a schema for storage in the ToolDefinition.
     */
    private function extractParametersFromSchema(array $schema): array
    {
        $parameters = [];
        
        if (isset($schema['properties'])) {
            foreach ($schema['properties'] as $name => $property) {
                $parameters[] = [
                    'name' => $name,
                    'type' => $property['type'] ?? 'string',
                    'description' => $property['description'] ?? '',
                    'required' => in_array($name, $schema['required'] ?? []),
                ];
            }
        }

        return $parameters;
    }

    /**
     * Requests approval for a pending tool definition.
     */
    public function requestApproval(ToolDefinition $toolDefinition): void
    {
        $toolDefinition->setStatus('pending_approval');
        $this->toolDefinitionRepo->save($toolDefinition, true);
    }

    /**
     * Approves a tool definition.
     */
    public function approveTool(ToolDefinition $toolDefinition): void
    {
        $toolDefinition->setStatus('approved');
        $toolDefinition->setUpdatedAt(new \DateTimeImmutable());
        $this->toolDefinitionRepo->save($toolDefinition, true);
    }
}
